### ISSUE TITLE
Dataloader with multiple deps behaves strangely

### ISSUE THREAD

**Issue by sooheon** [keechma/keechma-toolbox#1]
Building off of the [manually-call-dataloaders](https://github.com/retro/manually-call-dataloader-example/blob/master/src/cljs/dataloader_example/datasources.cljs) example, I added one more dependency to the :deps vector, [here](https://github.com/DMK-Labs/trendtracker/blob/ee7e8c54e88c1cdc9e2c3aedd622be4ba97b272d/src/cljs/trendtracker/datasources.cljs#L69).

I then expect a get-in [:params :dependency-key] operation (as seen [here](https://github.com/DMK-Labs/trendtracker/blob/ee7e8c54e88c1cdc9e2c3aedd622be4ba97b272d/src/cljs/trendtracker/datasources.cljs#L74)) to return the right data. 

For example, from [this](https://github.com/DMK-Labs/trendtracker/blob/ee7e8c54e88c1cdc9e2c3aedd622be4ba97b272d/src/cljs/trendtracker/datasources.cljs#L79) println, I expect `:cascader` to be a vector like `[:total]`, and `:date-range` to be a map like `{:curr [(js/moment) (js/moment)], :prev [...]}`,

However, inspecting the data looks more like this: 

<img width="1037" alt="screen shot 2018-01-16 at 12 20 02 pm" src="https://user-images.githubusercontent.com/302945/34970417-a6f74080-fab7-11e7-8e71-af5cc8d1012a.png">

Even though I give two different symbols in `(print "loading data..." range casc)`, the printed result repeats the same data.

What am I doing wrong here?

**Comment by sooheon** [comment]
FWIW, combining my `date-range` and `cascader` datasources into a single wrapper datasource fixes the issue, so I suspect it has to do with more than one datasource using the "existing-data-loader" trick, maybe? Something about `(:data prev)` in the datasource :params key just seems...unspecific.

**Comment by retro** [comment]
@sooheon I'll copy/paste the from Slack here so anyone else who might have the same problem can see what's going on. Please reopen the issue if you still see the same behavior.

I’ve updated the example repo, it works correctly for me https://github.com/retro/manually-call-dataloader-example .

Now, to explain why it was behaving weirdly and why my controller looks different than yours. 

There was an issue with the pipeline controllers API which meant that you weren’t able to use synchrnous `start` and `stop` lifecycle functions. When Keechma starts the route change dance (starting and stopping controllers), first it calls (sync) `stop` functions on all controllers that need to be stopped, then it calls (sync) `start` functions on all controllers that need to be started, and then it starts the `handler` function on all started controllers. Implementation can be found here - https://github.com/keechma/keechma/blob/master/src/keechma/controller_manager.cljs#L32 , but the important thing is that Keechma guarantees this behavior for all controllers.

Previously pipeline controllers were implemented just with the `handler` function which meant that their `:start` pipelines were always called asynchronously. Keechma doesn’t guarantee (by design) order in which the controllers will be started which means that something like this happened (order can be different as it’s aribtrary):

1. Dataloader controller started which started the dataloader (in this moment both `[:kv :cascader]` and `[:kv :date-range]` are nil)
2. Cascader controller’s `:start` pipeline is called which sets the `[:kv :cascader]` and restarts the dataloader
3. Date range controller’s `:start` pipeline is called which sets the `[:kv :date-range]` and restarts the dataloader

This resulted with 3 calls to dataloader before we make the real request.

In the last release of Keechma Toolbox, I’ve added ability to define synchronous `start` and `stop` functions for controllers (which have the same API as the normal controllers), and this is what I’m using in the example repo. You can see the commit here: https://github.com/keechma/keechma-toolbox/commit/5807d2a4310a407fc9ac4a11e3f7a77a92c7c556 . This also renames `:start` and `:stop` pipelines to `:on-start` and `:on-stop` while supporting the old API. Now you have an ability to synchronusly set `[:kv :cascader]` and `[:kv :date-range]` before the dataloader is started (since it’s started inside the `handler` function which is guaranteed to run after all `start` functions are done). The timeline now looks like this:

1. Cascader controller’s (sync) `start` function is called - this sets `[:kv :cascader]`
2. Date range controller’s (sync) `start` function is called - this sets ’[:kv :date-range]`
3. Dataloader is started - `[:kv :cascader]` and `[:kv :date-range]` already have their values set - which means that dataloader is started only once.

I hope this clears it, and please do ask if you have any more questions
